### ISSUE TITLE
Rasterio for new users

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DKaren/FLO-2D-Rasterizor#11]
Can we add an install rasterio on the plugin?

**Comment by rpachaly** [comment]
I've changed the rasterio to gdal. It is on branch. Feel free to merge it whenever you want. 
[remove_rasterio](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/tree/remove_rasterio)

* In this branch, I've changed the cell size (calculated internally) and the projection is set automatically based on the project crs when the dialog is shown.

**Comment by FLO-2DKaren** [comment]
Can you check the branch?  I think it had a *.pyc folder.

**Comment by rpachaly** [comment]
I don't see that. But do we need *.pyc files?

**Comment by FLO-2DKaren** [comment]
These two need to be removed from the git.  They will mess up QGIS loading.
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/20424460/aa169d78-6945-47bd-9887-b00e1dcee394)

**Comment by FLO-2DKaren** [comment]
the pychache needs to be added to GitIngore.

**Comment by rpachaly** [comment]
I created a branch [remove_pycache](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/tree/remove_cache) and removed these folders from the repository. It should work now.

**Comment by FLO-2DKaren** [comment]
We tested it yesterday on a client's computer.  It works good.
