### ISSUE TITLE
Packages installer

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DKaren/FLO-2D-Rasterizor#12]
I've updated a plugin in my QGIS and I received the following message:

![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/39889306/8b3927f9-740a-49dd-927e-0f5706f86d87)

We could add something like this to install the RASTERIO library when Rasterizor is installed.

**Comment by FLO-2DKaren** [comment]
Yeah, that's nice!!!  Great Idea.
Does MapCrafter need Rasterio?  Maybe we could just stop using Rasterio and use GDAL.  
I don't really think that Rasterio has an advantage.  I just used it because it was in the code I found online.

**Comment by rpachaly** [comment]
No, MapCrafter does not need rasterio. We can change rasterizor to GDAL.

But this Packages Installer could be used in the future, if we need to use an external library or something.

**Comment by FLO-2DKaren** [comment]
Yeah it's nice for sure.  I wonder if it works on h5py.  That's the hardest module to install.

**Comment by rpachaly** [comment]
Probably it works.
