### ISSUE TITLE
Output results comparison

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DKaren/FLO-2D-Rasterizor#17]
Add a tab to perform a quick output result comparison

**Comment by rpachaly** [comment]
@FLO-2DKaren 
The code is almost ready but I'm thinking about the symbology.
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/39889306/dcc43540-ec27-4584-832b-63b3a3bb9e16)

I'm using blue-green-red. I think that values close to 0 should be green. But if I use this blue-green-red symbology, the green will not be necessarily 0. I'm trying to normalize the data or something. If you have any idea... 

I'm going to push the branch this way. If we decide to change the symbology is something easy to change.

**Comment by FLO-2DKaren** [comment]
I think we can do this with the color ramp editor and color stops to achieve this.  I think you can set the greens from negative 0.01 to positive 0.01 and then you can use a data defined value to set the min and max.

**Comment by FLO-2DKaren** [comment]
If you have a qml file, Chat GPT suggests you change the raster renderer like this:
<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis hasScaleBasedVisibilityFlag="0" minScale="1e+08" maxScale="0" styleCategories="AllStyleCategories" version="3.28.7-Firenze">
  ...
  <rasterrenderer type="singlebandpseudocolor" alphaBand="-1" nodataColor="" opacity="1" classificationMax="[band1max]" classificationMin="[band1min]" band="1">
    ...
    <colorrampshader labelPrecision="6" clip="0" colorRampType="INTERPOLATED" minimumValue="[band1min]" classificationMode="2" maximumValue="[band1max]">
      ...
      <item color="#0000ff" label="-3.802800" value="[band1min]" alpha="255"/>
      <item color="#008000" label="-0.010000" value="-0.01" alpha="255"/>
      <item color="#008000" label="0.010000" value="0.01" alpha="255"/>
      <item color="#ff0000" label="7.289600" value="[band1max]" alpha="255"/>
      ...
    </colorrampshader>
    ...
  </rasterrenderer>
  ...
</qgis>

**Comment by rpachaly** [comment]
I've found a solution. Check this out:

Velocity difference: 
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/39889306/e75948b1-f54d-4d7b-b1c0-b2dc9cf81341)
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/39889306/93b92bd9-ff20-4434-8150-863e55708314)

Depth difference:
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/39889306/219ed788-9df4-4119-94e2-af5904e85901)
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/39889306/08750a37-1812-4026-a5e9-11307cbafd48)

I'm pushing the branch but I'll let you decide to merge or not.

**Comment by FLO-2DKaren** [comment]
Well we might have a new issue.  I'm picking up some nodata for some reason.

![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/20424460/413cf3dd-c8fd-4aa6-a4c5-a1dea1ccfd7a)

**Comment by rpachaly** [comment]
Weird. Which data are you using to do the difference?

**Comment by FLO-2DKaren** [comment]
oooh looks like it's LESSON 3 results with no data.  Wonder why?
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/20424460/caf28bf5-45ae-46b1-855b-7c1ca73a1af6)

**Comment by rpachaly** [comment]
I would say the issue is related to the minimum value (0.01) or projection

**Comment by FLO-2DKaren** [comment]
I think it's the minimum value being set to no data.  I don't think we want that.  We want min value adjusted in the raster color render but not removing the data.

**Comment by FLO-2DKaren** [comment]
MapCrafter is doing it too.
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/20424460/c79c939c-c7d4-4d3a-acba-0ae0cc18f69a)

**Comment by rpachaly** [comment]
Ok, I'm wrapping up the LEVEEDEFICIT here and I'll take a look into this.

**Comment by FLO-2DKaren** [comment]
I'm going to close this issue since I think the difference tool is OK.   I'll make a new issue with test data.
