### ISSUE TITLE
Update Metadata and other things

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DKaren/FLO-2D-Rasterizor#20]
Hi Robson,

I can't load the plugin.  Something wrong with the metadata but I can't see anything. 
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/20424460/4c988d82-0366-4420-b5ad-09d4ea1e1483)

- [x] Update the metadata.  Add you as author and email, Update version and changelog, 
- [x] Correct pull request issue.  There is a simple merge block.
- [x] Remove unnecessary files.  It looks like 3 or 4 files that could be deleted.

**Comment by FLO-2DKaren** [comment]
Found the MetaData issue.  There was a space missing in the change log easy to fix. 

We can update the metadata with this. 

version=0.3
author=Karen OBrien, Robson Pachaly
email=contact@flo-2d.com

changelog=
 <p>0.3
  - add diff tool
  - update style code
 <p>0.2
  - replace rasterio with GDAL
  - auto calc pixel size
  - auto CRS selector
  - apply styles
 <p>0.1
  - align to grid
  - generic styles
  - set pixel size and crs
  - requires rasterio

**Comment by rpachaly** [comment]
Fixed all these and deletes some unused files. I'm pushing the branch.
