### ISSUE TITLE
Necessary files

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DKaren/FLO-2D-Rasterizor#26]
Hi Robson,  

Since I started the rasterizor from the plugin builder, it probably has some unnecessary files.  What are your thoughts?

I don't think the help folder is used either since we don't have documentation.

![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/20424460/8ac400cf-b119-45e9-83cb-b78fe6dfbc31)

![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/20424460/711e06c7-bc41-48db-87c9-b4cbf79a2563)

Some of those are necessary for deployment but not for running the plugin on QGIS.   We could delete or add them to the Git Ignore?

**Comment by FLO-2DKaren** [comment]
Set Homepage to Wiki.

**Comment by rpachaly** [comment]
I deleted almost all files and the plugin is working just fine.
![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/39889306/91ee409f-8c67-4fbd-abcd-983ab85e20fa)

**Comment by rpachaly** [comment]
I'm going to set the homepage to wiki and push the branch.

**Comment by rpachaly** [comment]
It is on this [branch](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/tree/min_value)

**Comment by rpachaly** [comment]
This [branch](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/tree/removed_files)

**Comment by rpachaly** [comment]
The homepage is correct on the metadata but not on the repository plugin about. Maybe it is updated when it is uploaded to the repository?

**Comment by FLO-2DKaren** [comment]
I think it will be OK because I see it's good in the code.
