### ISSUE TITLE
CRS ID

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DKaren/FLO-2D-Rasterizor#28]
Since FLO-2D should never be performed on a LatLong coordinate system, we should Query the coordinate system when the default system is listed as the project coordinate system.

**Comment by rpachaly** [comment]
I did not find a good way to query the CRS. I used the following logic:

**Check if the project CRS is LatLong.** 

Yes -> Open the CRS selector and let the user select the correct CRS*
No -> Set the project CRS to Rasterizor

* if the user select another LatLong CRS, the process repeats in a loop until a projected CRS is selected.

**Comment by rpachaly** [comment]
It is on [branch](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/tree/crs_id)

If you like this approach, we can add it to MapCrafter.

**Comment by FLO-2DKaren** [comment]
I think a message would suffice.

You have selected Lat-Long as your coordinate system.  Are you sure about that?

And then the message buttons could say:

"Braving the Unknown" for OK and "Retreat to Safer Waters" for Cancel

Something a little snarky but in a funny way.

**Comment by FLO-2DKaren** [comment]
@rpachaly 

Hi Robson,  I never merged the CRS code.  Sorry I missed this but now it has a merge block because the files are both editing stuff.  Can you resolve the block and I'll merge it.

**Comment by rpachaly** [comment]
The conflict was in the metadata file. It is fixed. The pull request is created.

**Comment by FLO-2DKaren** [comment]
I figured it was the metadata.  I uploaded it to QGIS repo this afternoon.
