### ISSUE TITLE
Filter Raster Comparison 

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DKaren/FLO-2D-Rasterizor#32]
Filter the comboboxes to show only rasters and not all layers.

**Comment by FLO-2DKaren** [comment]
I think that's an object on the QGIS button list.  It's already there, you just have to select the correct button.

**Comment by rpachaly** [comment]
This was really easy. Fixed and merged on https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/commit/05b7f984942c176b899c96e80f4233fa635308e9
