### ISSUE TITLE
Python Error

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DKaren/FLO-2D-Rasterizor#6]
@rpachaly 
Hi Robson,
I had an error with this file.  It is much bigger and it has decimal value in the X and Y column.
That is normal.

EPSG:2868

[DEPTH.zip](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/files/11558759/DEPTH.zip)

        1       708377.50       876802.50          0.0000
        2       708377.50       876787.50          0.0000
        3       708377.50       876772.50          0.0000
        4       708377.50       876757.50          0.0000
        5       708377.50       876742.50          0.0000
        6       708377.50       876727.50          0.0000
        7       708377.50       876712.50          0.0000
        8       708377.50       876697.50          0.0000
        9       708377.50       876682.50          0.0000
       10       708377.50       876667.50          0.0000
       11       708377.50       876652.50          0.0000
       12       708377.50       876637.50          0.0000

Here is the error message:

2023-05-24T16:14:19     WARNING    Traceback (most recent call last):
              File "C:\Users/Alejandro Riano/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\rasterizor\rasterizor.py", line 302, in run
              table = pd.read_table(fn, names='g x y z'.split(), sep=r'\s+', index_col=0)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\io\parsers.py", line 765, in read_table
              return read_csv(**locals())
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
              return _read(filepath_or_buffer, kwds)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\io\parsers.py", line 458, in _read
              data = parser.read(nrows)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\io\parsers.py", line 1196, in read
              ret = self._engine.read(nrows)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\io\parsers.py", line 2231, in read
              index, names = self._make_index(data, alldata, names)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\io\parsers.py", line 1677, in _make_index
              index = self._agg_index(index)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\io\parsers.py", line 1770, in _agg_index
              arr, _ = self._infer_types(arr, col_na_values | col_na_fvalues)
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\io\parsers.py", line 1871, in _infer_types
              mask = algorithms.isin(values, list(na_values))
              File "C:\OSGeo4W\apps\Python39\lib\site-packages\pandas\core\algorithms.py", line 443, in isin
              if np.isnan(values).any():
             TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by rpachaly** [comment]
Hi Karen, 

I believe that this file is too large. Therefore, I had to split it in smaller files and then process each one separately. At the end, I merged all .tif files. I got a result here, but I'm not sure if it is correct. I'm sending a picture here and the .tif file for you to check. If this is not correct, do you have anything that I can use as a guide - the project domain for instance?

[output.zip](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/files/11559650/output.zip)

![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/39889306/d6967e8f-077d-46fd-99fb-7b44e6b79ad0)

**Comment by FLO-2DKaren** [comment]
@rpachaly 
That raster is wrong.  It should look kind of like a loaf of bread.

I don't think this is related to the size of the file.  Relative to LiDAR data, it's not even that big.  I do see that the problem happens around line 1,000,000.  It works if you keep line 1,000,000 but it doesn't work if you keep line 1,000,002.

I also noted that the error message was related to a failed NAN data type check.  Our numpy and pandas is using the datatype float32.   I wonder if that is the source of our error.  This data format is ascii by the way.

**Comment by FLO-2DKaren** [comment]
@rpachaly 

[dlg_sampling_xyz.zip](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/files/11568034/dlg_sampling_xyz.zip)

Hi Robson,  I got this script from our regular plugin.  It has the methodology that will eliminate the need for Pandas.  This comes from our LiDAR interpolation tool and I know it can do the job without memory issues and without splitting up the data.

Important things about our data.
1. Our cell size is generally known by the engineer so we may not need to calculate it.  We can add it to the Dialog.
2. Our data is always space delimited as:  ge, x y n  where GE is grid element number, x,y are coordinates, and n is the output parameter.  You can read this data directly into memory instead of reading it into Pandas Dataframe.  See the Bold below.
3. I'm not super familiar with rasterio but you don't need to warp or interpolate anything because this is just Feature to Raster conversion.  That might speed things up if you aren't doing a Warp or a Transformation.  

Take a look at the load methods below.  I made them **Bold**.

    def interpolate_from_lidar(self):
        s = QSettings()
        last_dir = s.value("FLO-2D/lastLIDARDir", "")
        lidar_files, __ = QFileDialog.getOpenFileNames(
            None,
            "Select LIDAR files",
            directory=last_dir,
            filter="*.TXT ; *.DAT;;Normal text file (*.txt;*.TXT) ;;*.DAT;;All files (*)",
        )

        if not lidar_files:
            return
        s.setValue("FLO-2D/lastLIDARDir", os.path.dirname(lidar_files[0]))

        try:
            QApplication.setOverrideCursor(Qt.WaitCursor)
            elevs = {}
            read_error = "Error reading files:\n\n"
            outside_grid, inside_grid = 0, 0

            gid_indx = {}
            cells = self.gutils.execute("SELECT fid, col, row FROM grid").fetchall()
            for cell in cells:
                gid_indx[cell[1], cell[2]] = [cell[0], 0.0, 0]

            start_time = time.time()

            statBar = self.iface.mainWindow().statusBar()
            statusLabel = QLabel()
            statBar.addWidget(statusLabel, 5)
            advanceBar = QProgressBar()
            advanceBar.setStyleSheet("QProgressBar::chunk { background-color: lightskyblue}")
            advanceBar.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)
            advanceBar.setMinimum(0)
            statBar.addWidget(advanceBar, 2)

            size = 0
            lines = 0
            for file in lidar_files:
                file_size = os.path.getsize(file)
                with open(file, "r") as f:
                    line = f.readline()

                    line_size = len(line) + 1
                size += file_size / line_size

            progress = self.uc.progress_bar2(
                "Reading " + "{:,}".format(int(size)) + " lines from " + str(len(lidar_files)) + " files...",
                0,
                len(lidar_files),
                0,
            )
            step = 50000
            for i, file in enumerate(lidar_files, 1):
                progress.setValue(i)
                n_commas = 0
                n_spaces = 0

                # See if comma or space delimited:
                with open(file, "r") as f:
                    while True:
                        line = f.readline()
                        line = line.replace("\t", "")
                        if line.strip() != "":
                            n_commas = line.count(",")
                            if n_commas == 0:
                                n_spaces = len(line.split())
                            break

                if n_commas != 0 or n_spaces != 0:
                    # Read file:
                    with open(file, "r") as f1:
                        try:
                            lines = f1.readlines()
                            n_lines = len(lines)
                            statusLabel.setText(
                                "Reading  "
                                + "{:,}".format(n_lines)
                                + "  lines from "
                                + "<FONT COLOR=blue>"
                                + os.path.basename(file)
                                + "</FONT>"
                            )
                            advanceBar.setMaximum(n_lines)

                            step = int(n_lines / 20)

                            if n_lines > step:
                                advanceBar.setValue(int(step / 2))
                                # self.iface.mainWindow().repaint()

                            for i, line in enumerate(lines, 1):
                                if int(i % step) == 0:
                                    advanceBar.setValue(i)
                                    qApp.processEvents()

                                **line = line.replace("\t", "")
                                if n_commas == 0:  # No commas, values separated by spaces.
                                    values = line.split()
                                    n_values = len(values)
                                    if n_values == 3:
                                        xpp, ypp, zpp = values
                                    elif n_values == 4:
                                        xpp, ypp, zpp, dummy = values
                                    elif n_values == 5:
                                        dummy1, xpp, ypp, zpp, dummy2 = values
                                    else:
                                        break
                                elif n_commas == 2:  # 3 columns.
                                    xpp, ypp, zpp = line.split(",")
                                elif n_commas == 3:  # 4 columns.
                                    xpp, ypp, zpp, dummy = line.split(",")
                                elif n_commas == 4:  # 5 columns.
                                    dummy1, xpp, ypp, zpp, dummy2 = line.split(",")
                                else:
                                    break

                                col = int((float(xpp) - self.xMinimum) / self.cell_size) + 2
                                row = int((float(ypp) - self.yMinimum) / self.cell_size) + 2**
                                if (col, row) in gid_indx:
                                    gid_indx[col, row][1] += float(zpp)
                                    gid_indx[col, row][2] += 1
                                    inside_grid += 1
                                else:
                                    outside_grid += 1

                        except ValueError:
                            read_error += os.path.basename(file) + " at line " + str(i) + "\n\n"

            self.uc.clear_bar_messages()
            statBar.removeWidget(statusLabel)
            statBar.removeWidget(advanceBar)
            qApp.processEvents()
            self.uc.bar_info("Updating grid elevations...")

            # Assign -9999 to all cell elevations prior to the assignment from LIDAR points:
            self.gutils.execute("UPDATE grid SET elevation = -9999;")

            # Update cell elevations from LIDAR points:
            nope = []
            cell_elev = []

            if inside_grid > 0:
                qry = "UPDATE grid SET elevation = ? WHERE fid = ?;"
                for gi in gid_indx.items():
                    if gi[1][2] != 0:
                        elevation = round(gi[1][1] / gi[1][2], 4)
                        cell_elev.append((elevation, gi[1][0]))
                    else:
                        nope.append((gi[1][0], gi[0][0], gi[0][1]))  # element, col, row
                self.gutils.execute_many(qry, cell_elev)

            self.uc.clear_bar_messages()
            QApplication.restoreOverrideCursor()

            end_time = time.time()
            time_passed = self.elapsed_time(start_time, end_time)
            self.uc.show_info(
                "Elevations assigned from LIDAR files.\n\n"
                + "{0:,d}".format(inside_grid)
                + " points inside the grid, and "
                + "{0:,d}".format(outside_grid)
                + " points outside."
                + "\n\n(Elapsed time: "
                + str(time_passed)
                + ")"
            )

            if read_error != "Error reading files:\n\n":
                self.uc.show_info(read_error)

            if nope:
                QApplication.setOverrideCursor(Qt.WaitCursor)
                elevs = [x[0] for x in cell_elev]
                mini = -9999
                mini2 = min(elevs)
                maxi = max(elevs)
                render_grid_elevations2(self.grid, True, mini, mini2, maxi)
                set_min_max_elevs(mini, maxi)
                self.lyrs.lyrs_to_repaint = [self.grid]
                self.lyrs.repaint_layers()

                self.process_non_interpolated_cells(nope, cell_elev)

            # self.lyrs.refresh_layers()
            self.lyrs.zoom_to_all()

            QApplication.restoreOverrideCursor()

        except Exception as e:
            self.uc.clear_bar_messages()
            QApplication.restoreOverrideCursor()
            # self.iface.messageBar().clearWidgets()
            self.uc.show_error("ERROR 140321.1653: importing LIDAR files failed!", e)
            return

**Comment by rpachaly** [comment]
I'm trying to understand and adapt this function. Where can I get this library? "from ..geopackage_utils import GeoPackageUtils"

**Comment by FLO-2DKaren** [comment]
The whole plugin is here: https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin

**Comment by rpachaly** [comment]
I took that function as an example and adapted. I need to do some minor changes/fixes to my code. Is this the expected raster?

![image](https://github.com/FLO-2DKaren/FLO-2D-Rasterizor/assets/39889306/28325e71-d2ec-479c-a22a-256ad9d22e27)

**Comment by FLO-2DKaren** [comment]
That looks correct.  Its a surface water depth raster for a 100yr rain on grid event.  It's the largest project that I have on my computer.
